# Generated by Django 3.0.6 on 2023-01-17 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roof', models.IntegerField()),
                ('office', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=100)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourapp.Departments')),
                ('employers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourapp.Employers')),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='employers',
            field=models.ManyToManyField(through='yourapp.Roles', to='yourapp.Employers'),
        ),
    ]
